# Generated by Django 5.0.1 on 2024-02-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='descripcion',
            new_name='ingreso',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='fecha',
        ),
    ]
