# Generated by Django 5.0.1 on 2024-02-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_gasto_fecha_alter_gasto_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
