# Generated by Django 5.0.1 on 2024-02-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_gasto_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivo',
            name='fecha_limite',
        ),
    ]
