# Generated by Django 5.0.1 on 2024-02-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_objetivo_fecha_limite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo',
            old_name='monto_objetivo',
            new_name='monto',
        ),
    ]
