# Generated by Django 5.0.1 on 2024-02-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
